# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_type', models.CharField(max_length=80)),
                ('people_total_tested_count', models.IntegerField(default=0, null=True)),
                ('cases', models.IntegerField(blank=True, default=0, null=True)),
                ('difference', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField()),
                ('combined_key', models.CharField(max_length=150)),
                ('country_region', models.CharField(max_length=150)),
                ('province_state', models.CharField(max_length=150)),
                ('admin2', models.CharField(max_length=200)),
                ('iso2', models.CharField(max_length=80)),
                ('iso3', models.CharField(max_length=80)),
                ('fips', models.IntegerField(default=0, null=True)),
                ('lat', models.FloatField(blank=True, default=0, null=True)),
                ('lon', models.FloatField(blank=True, default=0, null=True)),
                ('population_count', models.IntegerField(blank=True, null=True)),
                ('people_hospitalized', models.IntegerField(default=0, null=True)),
                ('data_source', models.CharField(max_length=90)),
                ('prep_flow_runtime', models.DateTimeField()),
            ],
        ),
    ]
