# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='admin2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
